/*
 * Copyright (C) 2001-2012 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */

struct EncodingTable {
    const char* m_Name;
    int m_Type;
};

static EncodingTable g_EncodingTable[] =
{
    {"ANSI_X3.4-1968", 0},
    {"iso-ir-6", 0},
    {"ANSI_X3.4-1986", 0},
    {"ISO_646.irv:1991", 0},
    {"ASCII", 0},
    {"ISO646-US", 0},
    {"US-ASCII", 0},
    {"us", 0},
    {"IBM367", 0},
    {"cp367", 0},
    {"csASCII", 0},

    {"windows-1250", 1},
    {"windows-1251", 2},
    {"windows-1252", 3},
    {"windows-1253", 4},
    {"windows-1254", 5},
    {"windows-1255", 6},
    {"windows-1256", 7},
    {"windows-1257", 8},
    {"windows-1258", 9},

    {"GBK", 10},
    {"CP936", 10},
    {"MS936", 10},
    {"windows-936", 10},

    {"ISO_8859-1:1987", 17},
    {"iso-ir-100", 17},
    {"ISO_8859-1", 17},
    {"ISO-8859-1", 17},
    {"latin1", 17},
    {"l1", 17},
    {"IBM819", 17},
    {"CP819", 17},
    {"csISOLatin1", 17},

    {"ISO_8859-2:1987", 18},
    {"iso-ir-101", 18},
    {"ISO_8859-2", 18},
    {"ISO-8859-2", 18},
    {"latin2", 18},
    {"l2", 18},
    {"csISOLatin2", 18},

    {"ISO_8859-3:1988", 19},
    {"iso-ir-109", 19},
    {"ISO_8859-3", 19},
    {"ISO-8859-3", 19},
    {"latin3", 19},
    {"l3", 19},
    {"csISOLatin3", 19},

    {"ISO_8859-4:1988", 20},
    {"iso-ir-110", 20},
    {"ISO_8859-4", 20},
    {"ISO-8859-4", 20},
    {"latin4", 20},
    {"l4", 20},
    {"csISOLatin4", 20},

    {"ISO_8859-5:1988", 21},
    {"iso-ir-144", 21},
    {"ISO_8859-5", 21},
    {"ISO-8859-5", 21},
    {"cyrillic", 21},
    {"csISOLatinCyrillic", 21},

    {"ISO_8859-6:1987", 22},
    {"iso-ir-127", 22},
    {"ISO_8859-6", 22},
    {"ISO-8859-6", 22},
    {"ECMA-114", 22},
    {"ASMO-708", 22},
    {"arabic", 22},
    {"csISOLatinArabic", 22},

    {"ISO_8859-7:1987", 23},
    {"iso-ir-126", 23},
    {"ISO_8859-7", 23},
    {"ISO-8859-7", 23},
    {"ELOT_928", 23},
    {"ECMA-118", 23},
    {"greek", 23},
    {"greek8", 23},
    {"csISOLatinGreek", 23},

    {"ISO_8859-8:1988", 24},
    {"iso-ir-138", 24},
    {"ISO_8859-8", 24},
    {"ISO-8859-8", 24},
    {"hebrew", 24},
    {"csISOLatinHebrew", 24},

    {"ISO_8859-9:1989", 25},
    {"iso-ir-148", 25},
    {"ISO_8859-9", 25},
    {"ISO-8859-9", 25},
    {"latin5", 25},
    {"l5", 25},
    {"csISOLatin5", 25},

    {"ISO-8859-10", 26},
    {"iso-ir-157", 26},
    {"l6", 26},
    {"ISO_8859-10:1992", 26},
    {"csISOLatin6", 26},
    {"latin6", 26},

    {"KS_C_5601-1987", 43},
    {"iso-ir-149", 43},
    {"KS_C_5601-1989", 43},
    {"KSC_5601", 43},
    {"korean", 43},
    {"csKSC56011987", 43},

    {"ISO-2022-KR", 16},
    {"csISO2022KR", 16},

    {"EUC-KR", 12},
    {"csEUCKR", 12},

    {"ISO-2022-JP", 15},
    {"csISO2022JP", 15},

    {"GB_2312-80", 41},
    {"iso-ir-58", 41},
    {"chinese", 41},
    {"csISO58GB231280", 41},

    {"UTF-8", 40},

    {"ISO-8859-13", 28},

    {"ISO-8859-14", 29},
    {"iso-ir-199", 29},
    {"ISO_8859-14:1998", 29},
    {"ISO_8859-14", 29},
    {"latin8", 29},
    {"iso-celtic", 29},
    {"l8", 29},

    {"ISO-8859-15", 30},
    {"ISO_8859-15", 30},
    {"Latin-9", 30},

    {"ISO-8859-16", 31},
    {"iso-ir-226", 31},
    {"ISO_8859-16:2001", 31},
    {"ISO_8859-16", 31},
    {"latin10", 31},
    {"l10", 31},

    {"GB2312", 13},
    {"csGB2312", 13},

    {"Big5", 42},
    {"csBig5", 42},

    {"KOI8-R", 38},
    {"csKOI8R", 38},
    {"HZ-GB-2312", 38},

    {"IBM866", 33},
    {"cp866", 33},
    {"866", 33},
    {"csIBM866", 33},

    {"KOI8-U", 36},

    {"ISO-10646-UCS-2", 38},
    {"csUnicode", 38},
    {"UTF-16BE", 38},
    {"UTF-16LE", 38},
    {"UTF-16", 38},

    {"UTF-7", 39},

    {NULL,-1}
};

struct MimeTypeTable {
    const char* m_Extension;
    const char* m_MimeType;
};

static MimeTypeTable g_MimeTypeTable[] =
{
    {"a", "application/octet-stream"},
    {"ai", "application/postscript"},
    {"aif", "audio/x-aiff"},
    {"aifc", "audio/x-aiff"},
    {"aiff", "audio/x-aiff"},
    {"au", "audio/basic"},
    {"avi", "video/x-msvideo"},
    {"bat", "text/plain"},
    {"bcpio", "application/x-bcpio"},
    {"bin", "application/octet-stream"},
    {"bmp", "image/x-ms-bmp"},
    {"c", "text/plain"},
    {"cdf", "application/x-cdf"},
    {"cdf", "application/x-netcdf"},
    {"cpio", "application/x-cpio"},
    {"csh", "application/x-csh"},
    {"css", "text/css"},
    {"dll", "application/octet-stream"},
    {"doc", "application/msword"},
    {"dot", "application/msword"},
    {"dvi", "application/x-dvi"},
    {"eml", "message/rfc822"},
    {"eps", "application/postscript"},
    {"etx", "text/x-setext"},
    {"exe", "application/octet-stream"},
    {"gif", "image/gif"},
    {"gtar", "application/x-gtar"},
    {"h", "text/plain"},
    {"hdf", "application/x-hdf"},
    {"htm", "text/html"},
    {"html", "text/html"},
    {"ief", "image/ief"},
    {"jpe", "image/jpeg"},
    {"jpeg", "image/jpeg"},
    {"jpg", "image/jpeg"},
    {"js", "application/x-javascript"},
    {"ksh", "text/plain"},
    {"latex", "application/x-latex"},
    {"m1v", "video/mpeg"},
    {"man", "application/x-troff-man"},
    {"me", "application/x-troff-me"},
    {"mht", "message/rfc822"},
    {"mhtml", "message/rfc822"},
    {"mif", "application/x-mif"},
    {"mov", "video/quicktime"},
    {"movie", "video/x-sgi-movie"},
    {"mp2", "audio/mpeg"},
    {"mp3", "audio/mpeg"},
    {"mpa", "video/mpeg"},
    {"mpe", "video/mpeg"},
    {"mpeg", "video/mpeg"},
    {"mpg", "video/mpeg"},
    {"ms", "application/x-troff-ms"},
    {"nc", "application/x-netcdf"},
    {"nws", "message/rfc822"},
    {"o", "application/octet-stream"},
    {"obj", "application/octet-stream"},
    {"oda", "application/oda"},
    {"p12", "application/x-pkcs12"},
    {"p7c", "application/pkcs7-mime"},
    {"pbm", "image/x-portable-bitmap"},
    {"pdf", "application/pdf"},
    {"pfx", "application/x-pkcs12"},
    {"pgm", "image/x-portable-graymap"},
    {"pl", "text/plain"},
    {"png", "image/png"},
    {"pnm", "image/x-portable-anymap"},
    {"pot", "application/vnd.ms-powerpoint"},
    {"ppa", "application/vnd.ms-powerpoint"},
    {"ppm", "image/x-portable-pixmap"},
    {"pps", "application/vnd.ms-powerpoint"},
    {"ppt", "application/vnd.ms-powerpoint"},
    {"ps", "application/postscript"},
    {"pwz", "application/vnd.ms-powerpoint"},
    {"py", "text/x-python"},
    {"pyc", "application/x-python-code"},
    {"pyo", "application/x-python-code"},
    {"qt", "video/quicktime"},
    {"ra", "audio/x-pn-realaudio"},
    {"ram", "application/x-pn-realaudio"},
    {"ras", "image/x-cmu-raster"},
    {"rdf", "application/xml"},
    {"rgb", "image/x-rgb"},
    {"roff", "application/x-troff"},
    {"rtx", "text/richtext"},
    {"sgm", "text/x-sgml"},
    {"sgml", "text/x-sgml"},
    {"sh", "application/x-sh"},
    {"shar", "application/x-shar"},
    {"snd", "audio/basic"},
    {"so", "application/octet-stream"},
    {"src", "application/x-wais-source"},
    {"sv4cpio", "plication/x-sv4cpio"},
    {"sv4crc", "plication/x-sv4crc"},
    {"swf", "application/x-shockwave-flash"},
    {"t", "application/x-troff"},
    {"tar", "application/x-tar"},
    {"tcl", "application/x-tcl"},
    {"tex", "application/x-tex"},
    {"texi", "application/x-texinfo"},
    {"texinfo", "plication/x-texinfo"},
    {"tif", "image/tiff"},
    {"tiff", "image/tiff"},
    {"tr", "application/x-troff"},
    {"tsv", "text/tab-separated-values"},
    {"txt", "text/plain"},
    {"ustar", "application/x-ustar"},
    {"vcf", "text/x-vcard"},
    {"wav", "audio/x-wav"},
    {"wiz", "application/msword"},
    {"wsdl", "application/xml"},
    {"xbm", "image/x-xbitmap"},
    {"xlb", "application/vnd.ms-excel"},
    {"xls", "application/excel"},
    {"xls", "application/vnd.ms-excel"},
    {"xml", "text/xml"},
    {"xpdl", "application/xml"},
    {"xpm", "image/x-xpixmap"},
    {"xsl", "application/xml"},
    {"xwd", "image/x-xwindowdump"},
    {"zip", "application/zip"},
    {"jpg", "image/jpg"},
    {"mid", "audio/midi"},
    {"midi", "audio/midi"},
    {"pct", "image/pict"},
    {"pic", "image/pict"},
    {"pict", "image/pict"},
    {"rtf", "application/rtf"},
    {"xul", "text/xul"},

    {NULL,NULL}
};
